# Generated by Django 5.2.16 on 2026-07-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0005_party_assigned_agent_alter_party_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='foundation.catalogitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['item'], name='inventory_s_item_id_fb3b61_idx')],
                'unique_together': {('item', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('adjust', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valuation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='foundation.catalogitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['item', '-at'], name='inventory_s_item_id_5ee841_idx'), models.Index(fields=['warehouse', '-at'], name='inventory_s_warehou_6a2c06_idx')],
            },
        ),
    ]
