# Generated by Django 5.2.16 on 2026-07-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'ordering': ['item_id', 'warehouse_id']},
        ),
    ]
