# Generated by Django 5.2.16 on 2026-07-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0004_tenantuser_reports_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_threshold_min', models.PositiveIntegerField(default=15)),
                ('geofence_radius_m', models.PositiveIntegerField(default=150)),
                ('auto_punchout_enabled', models.BooleanField(default=True)),
                ('auto_punchout_time', models.TimeField(default='18:00')),
                ('interval_moving_s', models.PositiveIntegerField(default=15)),
                ('interval_idle_s', models.PositiveIntegerField(default=120)),
                ('upload_interval_s', models.PositiveIntegerField(default=60)),
                ('track_window_start', models.TimeField(blank=True, null=True)),
                ('track_window_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tracking settings',
            },
        ),
        migrations.CreateModel(
            name='DeviceDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(db_index=True, max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('os_version', models.CharField(blank=True, max_length=60)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_diagnostics', to='foundation.tenantuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='tracking_de_agent_i_78a881_idx'), models.Index(fields=['event', '-created_at'], name='tracking_de_event_fe5037_idx')],
            },
        ),
        migrations.CreateModel(
            name='DutyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out_type', models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=6)),
                ('start_location', models.JSONField(blank=True, default=dict)),
                ('end_location', models.JSONField(blank=True, default=dict)),
                ('punch_in_selfie', models.URLField(blank=True, max_length=1000)),
                ('location_track', models.JSONField(blank=True, default=list)),
                ('mock_detected', models.BooleanField(default=False)),
                ('mock_point_count', models.IntegerField(default=0)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('offline_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('distance_traveled_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allowance_basis', models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office')], max_length=10)),
                ('edit_logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_days', to='foundation.tenantuser')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['agent', '-date'], name='tracking_du_agent_i_58fa93_idx')],
                'unique_together': {('agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('routes', models.JSONField(blank=True, default=list)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visit_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_history', to='foundation.tenantuser')),
            ],
            options={
                'verbose_name_plural': 'Route histories',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['agent', '-date'], name='tracking_ro_agent_i_d312d9_idx')],
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
