# Generated by Django 5.2.16 on 2026-07-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_eventdelivery'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('batch_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('source', models.CharField(default='Manual', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-from_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('workstation_type', models.CharField(choices=[('machine', 'Machine'), ('assembly', 'Assembly'), ('packaging', 'Packaging'), ('quality', 'Quality Control')], default='machine', max_length=30)),
                ('capacity', models.DecimalField(decimal_places=2, default=0, help_text='Units per hour', max_digits=12)),
                ('operating_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('power_consumption', models.DecimalField(decimal_places=2, default=0, help_text='kWh', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BOMOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=200)),
                ('time_in_mins', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operating_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.billofmaterials')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_operations', to='production.workstation')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='production.productionplan'),
        ),
        migrations.CreateModel(
            name='ProductionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('planned_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('produced_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='foundation.catalogitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('operation_name', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('for_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('completed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='foundation.tenantuser')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='production.bomoperation')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='production.workorder')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='production.workstation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
