import {
  Contact,
  Users,
  Navigation,
  ReceiptText,
  FileText,
  Boxes,
  Factory,
  ShoppingCart,
  Landmark,
  Share2,
  BarChart3,
  Smartphone,
  RefreshCw,
  LayoutGrid,
  MonitorSmartphone,
  WifiOff,
  ClipboardCheck,
  Warehouse,
  Wallet,
  Database,
  BadgeCheck,
  ShieldCheck,
  KeyRound,
  Languages,
  Bell,
  Lock,
  MapPin,
  Layers,
  ShoppingBasket,
  Truck,
  Pill,
  Sparkles,
  Shirt,
  HardHat,
  Sprout,
  Building2,
  CalendarCheck,
  Plane,
  Cloud,
  LifeBuoy,
  User,
  Phone,
  Mail,
  Clock,
  Headphones,
  Send,
  Upload,
  MessageSquare,
  Compass,
  Maximize2,
  CheckCircle2,
  ExternalLink,
  ArrowRight,
  Play,
  Briefcase,
  Info,
  Cpu,
  Inbox,
  MonitorPlay,
  Plus,
  AlertCircle,
  Barcode,
  Calculator,
  Store,
  Percent,
  Scan,
  Receipt,
  Calendar,
  CheckSquare,
  Target,
  TrendingUp,
  ArrowRightLeft,
  ChevronRight,
  ChevronDown,
  Check,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  Contact,
  Users,
  Navigation,
  ReceiptText,
  FileText,
  Boxes,
  Factory,
  ShoppingCart,
  Landmark,
  Share2,
  BarChart3,
  Smartphone,
  RefreshCw,
  LayoutGrid,
  MonitorSmartphone,
  WifiOff,
  ClipboardCheck,
  Warehouse,
  Wallet,
  Database,
  BadgeCheck,
  ShieldCheck,
  KeyRound,
  Languages,
  Bell,
  Lock,
  MapPin,
  Layers,
  ShoppingBasket,
  Truck,
  Pill,
  Sparkles,
  Shirt,
  HardHat,
  Sprout,
  Building2,
  CalendarCheck,
  Plane,
  Cloud,
  LifeBuoy,
  User,
  Phone,
  Mail,
  Clock,
  Headphones,
  Send,
  Upload,
  MessageSquare,
  Compass,
  Maximize2,
  CheckCircle2,
  ExternalLink,
  ArrowRight,
  Play,
  Briefcase,
  Info,
  // Cpu was referenced by the Electronics industry but never mapped, so it had
  // been falling back to the generic Layers glyph.
  Cpu,
  Inbox,
  MonitorPlay,
  Plus,
  // Used by the contact form's error banner - was falling back to Layers.
  AlertCircle,
  Barcode,
  Calculator,
  Store,
  Percent,
  Scan,
  Receipt,
  // Module walkthrough step icons - these were referenced by modulePages.ts
  // but never mapped, so they silently fell back to the Layers glyph.
  Calendar,
  CheckSquare,
  Target,
  TrendingUp,
  ArrowRightLeft,
  // Used by the walkthrough module switcher - was falling back to Layers.
  ChevronRight,
  // Used by the mobile module dropdown.
  ChevronDown,
  Check,
};

export default function Icon({
  name,
  className,
  strokeWidth = 1.6,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = map[name] ?? Layers;
  return <Cmp className={className} strokeWidth={strokeWidth} />;
}
