# Generated by Django 5.2.16 on 2026-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_seed_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
