# Generated by Django 5.2.16 on 2026-07-21 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_provisioningjob_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('version_code', models.PositiveIntegerField(unique=True)),
                ('apk_url', models.URLField(blank=True, max_length=1000)),
                ('release_notes', models.TextField(blank=True)),
                ('force_update', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
    ]
