# Generated by Django 5.2.16 on 2026-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=500)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('from_email', models.CharField(blank=True, max_length=200)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('sms_api_key', models.CharField(blank=True, max_length=500)),
                ('sms_sender_id', models.CharField(blank=True, max_length=20)),
                ('sms_entity_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform messaging configuration',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], db_index=True, max_length=8)),
                ('trigger_key', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('module_code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('dlt_template_id', models.CharField(blank=True, max_length=64)),
                ('available_variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel', 'category', 'name'],
                'indexes': [models.Index(fields=['channel', 'module_code'], name='control_mes_channel_56a4e6_idx')],
                'unique_together': {('channel', 'trigger_key')},
            },
        ),
    ]
