# Generated by Django 5.2.16 on 2026-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_seed_full_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmessagingconfig',
            name='fcm_server_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='platformmessagingconfig',
            name='sms_endpoint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='platformmessagingconfig',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('', 'Not configured'), ('msg91', 'MSG91'), ('textlocal', 'Textlocal'), ('generic', 'Generic HTTP (custom URL)')], max_length=20),
        ),
    ]
