# Generated by Django 5.2.16 on 2026-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_push_and_sms_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmessagingconfig',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('', 'Not configured'), ('smsgatewayhub', 'SMSGatewayHub'), ('msg91', 'MSG91'), ('textlocal', 'Textlocal'), ('generic', 'Generic HTTP (custom URL)')], max_length=20),
        ),
    ]
