# Generated by Django 5.2.16 on 2026-08-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_smsgatewayhub_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformmessagingconfig',
            name='fcm_server_key',
        ),
        migrations.AddField(
            model_name='platformmessagingconfig',
            name='fcm_service_account',
            field=models.TextField(blank=True),
        ),
    ]
