# Generated by Django 5.2.16 on 2026-07-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_eventdelivery_modules_at_emit_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('field_order_id__isnull', False)), fields=('field_order_id',), name='uniq_sales_order_per_field_order'),
        ),
    ]
