# Generated by Django 5.2.16 on 2026-07-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0004_tenantuser_reports_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('against_invoice', models.CharField(blank=True, max_length=64)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('client_uuid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='foundation.tenantuser')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='foundation.party')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40, unique=True)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='new', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('client_uuid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_orders', to='foundation.tenantuser')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_orders', to='foundation.party')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FieldOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.catalogitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='field.fieldorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('visit_target', models.IntegerField(default=0)),
                ('order_target', models.IntegerField(default=0)),
                ('stock_request_target', models.IntegerField(default=0)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_request_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_client_target', models.IntegerField(default=0)),
                ('login_hours_target', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pincodes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='foundation.tenantuser')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalesCityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('visit_target', models.IntegerField(default=0)),
                ('order_target', models.IntegerField(default=0)),
                ('stock_request_target', models.IntegerField(default=0)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_request_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_client_target', models.IntegerField(default=0)),
                ('login_hours_target', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_targets', to='field.salestarget')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('actual_checkin_time', models.DateTimeField(blank=True, null=True)),
                ('actual_checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_location', models.JSONField(blank=True, default=dict)),
                ('checkout_location', models.JSONField(blank=True, default=dict)),
                ('gps_verified', models.BooleanField(default=False)),
                ('visit_type', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('checkout_notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('transport_mode', models.CharField(choices=[('bike', 'Bike'), ('walk', 'Walk'), ('car', 'Car')], default='bike', max_length=10)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('skip_reason', models.TextField(blank=True)),
                ('reschedule_reason', models.TextField(blank=True)),
                ('rescheduled_to', models.DateField(blank=True, null=True)),
                ('rescheduled_time', models.TimeField(blank=True, null=True)),
                ('checkin_selfie', models.URLField(blank=True, max_length=1000)),
                ('voice_note_url', models.URLField(blank=True, max_length=1000)),
                ('client_uuid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='foundation.tenantuser')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='foundation.party')),
            ],
            options={
                'ordering': ['-visit_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('image_type', models.CharField(default='shop_image', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='field.visit')),
            ],
        ),
        migrations.AddIndex(
            model_name='fieldorder',
            index=models.Index(fields=['agent', '-order_date'], name='field_field_agent_i_04d3a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='field_unique_default_target'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', True), ('is_default', False)), fields=('month', 'year'), name='field_unique_global_monthly_target'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', False), ('is_default', False)), fields=('agent', 'month', 'year'), name='field_unique_agent_monthly_target'),
        ),
        migrations.AlterUniqueTogether(
            name='salescitytarget',
            unique_together={('target', 'city')},
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['agent', 'visit_date'], name='field_visit_agent_i_af0b20_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', '-visit_date'], name='field_visit_status_eaa0f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid', ''), _negated=True), fields=('client_uuid',), name='field_visit_unique_client_uuid'),
        ),
    ]
