# Generated by Django 5.2.16 on 2026-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
        ('foundation', '0004_tenantuser_reports_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-collected_at']},
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid', ''), _negated=True), fields=('client_uuid',), name='field_collection_unique_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='fieldorder',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid', ''), _negated=True), fields=('client_uuid',), name='field_order_unique_client_uuid'),
        ),
    ]
