# Generated by Django 5.2.16 on 2026-07-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='appearance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='setup_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
