# Generated by Django 5.2.16 on 2026-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_orgsettings_appearance_orgsettings_setup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='aadhaar_card',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='pan_card',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
