# Generated by Django 5.2.16 on 2026-07-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_tenantuser_aadhaar_card_tenantuser_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='foundation.tenantuser'),
        ),
    ]
