# Generated by Django 5.2.16 on 2026-07-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_tenantuser_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parties', to='foundation.tenantuser'),
        ),
        migrations.AlterField(
            model_name='party',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Customer & Supplier'), ('prospect', 'Prospect')], default='customer', max_length=16),
        ),
    ]
