# Generated by Django 5.2.16 on 2026-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_tenantuser_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('subscriber', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed (will retry)'), ('abandoned', 'Abandoned (max attempts)')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event deliveries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='foundation__status_0dc4c5_idx'), models.Index(fields=['event', 'status'], name='foundation__event_e09644_idx')],
            },
        ),
    ]
