# Generated by Django 5.2.16 on 2026-07-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_eventdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email configuration',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('trigger_key', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('available_variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('sender_id', models.CharField(blank=True, max_length=20)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS configuration',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('trigger_key', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('dlt_template_id', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='active_font',
            field=models.CharField(default='roboto', max_length=64),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='date_format',
            field=models.CharField(default='dd/MM/yyyy', max_length=32),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='default_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='default_operating_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='fiscal_day_start',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='office_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='office_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='operating_cities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='registration_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_full_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('version_code', models.PositiveIntegerField(unique=True)),
                ('apk_url', models.URLField(blank=True, max_length=1000)),
                ('release_notes', models.TextField(blank=True)),
                ('force_update', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_versions', to='foundation.tenantuser')),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
        migrations.CreateModel(
            name='RoleQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_slug', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(max_length=60)),
                ('path', models.CharField(max_length=200)),
                ('module_key', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['role_slug', 'order', 'id'],
                'unique_together': {('role_slug', 'path')},
            },
        ),
        migrations.CreateModel(
            name='UserQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('path', models.CharField(max_length=200)),
                ('module_key', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='foundation.tenantuser')),
            ],
            options={
                'ordering': ['user', 'order', 'id'],
                'unique_together': {('user', 'path')},
            },
        ),
    ]
