# Generated by Django 5.2.16 on 2026-07-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_emailconfiguration_emailtemplate_smsconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hsn_codes', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('is_base_unit', models.BooleanField(default=False)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UOM',
                'ordering': ['uom_name'],
            },
        ),
    ]
