# Generated by Django 5.2.16 on 2026-07-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0009_taxslab_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdelivery',
            name='modules_at_emit',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='eventdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed (will retry)'), ('abandoned', 'Abandoned (max attempts)'), ('skipped_unentitled', 'Skipped (module no longer entitled)')], db_index=True, default='pending', max_length=20),
        ),
    ]
