# Generated by Django 5.2.16 on 2026-07-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_eventdelivery_modules_at_emit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppVersion',
        ),
    ]
