# Generated by Django 5.2.16 on 2026-07-21 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0011_delete_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('username_attempted', models.CharField(blank=True, max_length=254)),
                ('user_role', models.CharField(blank=True, max_length=64)),
                ('event', models.CharField(choices=[('login', 'Login'), ('failed_login', 'Failed login'), ('logout', 'Logout')], db_index=True, default='login', max_length=16)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('method', models.CharField(default='password', max_length=20)),
                ('platform', models.CharField(default='web', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('location_resolved', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to='foundation.tenantuser')),
            ],
            options={
                'verbose_name_plural': 'Login activity',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='foundation__event_18eb77_idx')],
            },
        ),
    ]
