// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Hybrid icon registry: animated (@animateicons/react) where available, else static (lucide-react).
// Every glyph renders an SVG with stroke="currentColor", so icons follow the active color scheme.

import type { ComponentType } from "react";
import { ActivityIcon as Av_Activity } from "@/vendor/animateicons/lucide";
import { ArrowDownUpIcon as Av_ArrowDownUp } from "@/vendor/animateicons/lucide";
import { AudioLinesIcon as Av_AudioLines } from "@/vendor/animateicons/lucide";
import { BadgeDollarIcon as Av_BadgeDollar } from "@/vendor/animateicons/lucide";
import { BellIcon as Av_Bell } from "@/vendor/animateicons/lucide";
import { BellRingIcon as Av_BellRing } from "@/vendor/animateicons/lucide";
import { BookOpenIcon as Av_BookOpen } from "@/vendor/animateicons/lucide";
import { BoxesIcon as Av_Boxes } from "@/vendor/animateicons/lucide";
import { ChartColumnIcon as Av_ChartColumn } from "@/vendor/animateicons/lucide";
import { ChartLineIcon as Av_ChartLine } from "@/vendor/animateicons/lucide";
import { CheckIcon as Av_Check } from "@/vendor/animateicons/lucide";
import { ChevronDownIcon as Av_ChevronDown } from "@/vendor/animateicons/lucide";
import { ChevronLeftIcon as Av_ChevronLeft } from "@/vendor/animateicons/lucide";
import { ChevronRightIcon as Av_ChevronRight } from "@/vendor/animateicons/lucide";
import { ChevronUpIcon as Av_ChevronUp } from "@/vendor/animateicons/lucide";
import { CircleCheckIcon as Av_CircleCheck } from "@/vendor/animateicons/lucide";
import { CircleCheckBigIcon as Av_CircleCheckBig } from "@/vendor/animateicons/lucide";
import { CirclePlusIcon as Av_CirclePlus } from "@/vendor/animateicons/lucide";
import { ClipboardIcon as Av_Clipboard } from "@/vendor/animateicons/lucide";
import { CloudUploadIcon as Av_CloudUpload } from "@/vendor/animateicons/lucide";
import { ContactIcon as Av_Contact } from "@/vendor/animateicons/lucide";
import { CopyIcon as Av_Copy } from "@/vendor/animateicons/lucide";
import { CreditCardIcon as Av_CreditCard } from "@/vendor/animateicons/lucide";
import { DashboardIcon as Av_Dashboard } from "@/vendor/animateicons/lucide";
import { DollarSignIcon as Av_DollarSign } from "@/vendor/animateicons/lucide";
import { DownloadIcon as Av_Download } from "@/vendor/animateicons/lucide";
import { EllipsisVerticalIcon as Av_EllipsisVertical } from "@/vendor/animateicons/lucide";
import { ExternalLinkIcon as Av_ExternalLink } from "@/vendor/animateicons/lucide";
import { EyeIcon as Av_Eye } from "@/vendor/animateicons/lucide";
import { EyeOffIcon as Av_EyeOff } from "@/vendor/animateicons/lucide";
import { GlobeIcon as Av_Globe } from "@/vendor/animateicons/lucide";
import { HeadsetIcon as Av_Headset } from "@/vendor/animateicons/lucide";
import { HouseIcon as Av_House } from "@/vendor/animateicons/lucide";
import { IndianRupeeIcon as Av_IndianRupee } from "@/vendor/animateicons/lucide";
import { InfoIcon as Av_Info } from "@/vendor/animateicons/lucide";
import { LayoutGridIcon as Av_LayoutGrid } from "@/vendor/animateicons/lucide";
import { LayoutListIcon as Av_LayoutList } from "@/vendor/animateicons/lucide";
import { LockIcon as Av_Lock } from "@/vendor/animateicons/lucide";
import { LogoutIcon as Av_Logout } from "@/vendor/animateicons/lucide";
import { MailIcon as Av_Mail } from "@/vendor/animateicons/lucide";
import { MapPinIcon as Av_MapPin } from "@/vendor/animateicons/lucide";
import { MenuIcon as Av_Menu } from "@/vendor/animateicons/lucide";
import { MessageCircleIcon as Av_MessageCircle } from "@/vendor/animateicons/lucide";
import { MicIcon as Av_Mic } from "@/vendor/animateicons/lucide";
import { MinusIcon as Av_Minus } from "@/vendor/animateicons/lucide";
import { PhoneIcon as Av_Phone } from "@/vendor/animateicons/lucide";
import { PlayIcon as Av_Play } from "@/vendor/animateicons/lucide";
import { PlusIcon as Av_Plus } from "@/vendor/animateicons/lucide";
import { SearchIcon as Av_Search } from "@/vendor/animateicons/lucide";
import { SendIcon as Av_Send } from "@/vendor/animateicons/lucide";
import { SettingsIcon as Av_Settings } from "@/vendor/animateicons/lucide";
import { ShieldCheckIcon as Av_ShieldCheck } from "@/vendor/animateicons/lucide";
import { ShieldUserIcon as Av_ShieldUser } from "@/vendor/animateicons/lucide";
import { ShoppingBagIcon as Av_ShoppingBag } from "@/vendor/animateicons/lucide";
import { ShoppingCartIcon as Av_ShoppingCart } from "@/vendor/animateicons/lucide";
import { SignalIcon as Av_Signal } from "@/vendor/animateicons/lucide";
import { SlidersHorizontalIcon as Av_SlidersHorizontal } from "@/vendor/animateicons/lucide";
import { Trash2Icon as Av_Trash2 } from "@/vendor/animateicons/lucide";
import { TrendingDownIcon as Av_TrendingDown } from "@/vendor/animateicons/lucide";
import { TrendingUpIcon as Av_TrendingUp } from "@/vendor/animateicons/lucide";
import { TriangleAlertIcon as Av_TriangleAlert } from "@/vendor/animateicons/lucide";
import { UploadIcon as Av_Upload } from "@/vendor/animateicons/lucide";
import { UserIcon as Av_User } from "@/vendor/animateicons/lucide";
import { UserCheckIcon as Av_UserCheck } from "@/vendor/animateicons/lucide";
import { UserLockIcon as Av_UserLock } from "@/vendor/animateicons/lucide";
import { UserPlusIcon as Av_UserPlus } from "@/vendor/animateicons/lucide";
import { UsersIcon as Av_Users } from "@/vendor/animateicons/lucide";
import { UsersRoundIcon as Av_UsersRound } from "@/vendor/animateicons/lucide";
import { WalletIcon as Av_Wallet } from "@/vendor/animateicons/lucide";
import { WifiIcon as Av_Wifi } from "@/vendor/animateicons/lucide";
import { XIcon as Av_X } from "@/vendor/animateicons/lucide";
import FallbackIcon from "./FallbackIcon";

export type IconComponent = ComponentType<{ size?: number; className?: string }>;
interface IconEntry { C: IconComponent; animated: boolean; anim?: string; }

export const ICON_MAP: Record<string, IconEntry> = {
  "AccessTime": { C: FallbackIcon, animated: false, anim: "pop" },
  "AccountBalance": { C: FallbackIcon, animated: false, anim: "pop" },
  "AccountBalanceWallet": { C: Av_Wallet, animated: true },
  "AccountTree": { C: FallbackIcon, animated: false, anim: "pop" },
  "Add": { C: Av_Plus, animated: true },
  "AddBox": { C: FallbackIcon, animated: false, anim: "bounce" },
  "AddCircleOutline": { C: Av_CirclePlus, animated: true },
  "AddPhotoAlternate": { C: FallbackIcon, animated: false, anim: "bounce" },
  "AddShoppingCart": { C: Av_ShoppingCart, animated: true },
  "AdminPanelSettings": { C: Av_ShieldUser, animated: true },
  "Android": { C: FallbackIcon, animated: false, anim: "pop" },
  "ArrowBack": { C: FallbackIcon, animated: false, anim: "slide" },
  "ArrowDownward": { C: FallbackIcon, animated: false, anim: "bounce" },
  "ArrowForward": { C: FallbackIcon, animated: false, anim: "slide" },
  "ArrowUpward": { C: FallbackIcon, animated: false, anim: "bounce" },
  "Assessment": { C: Av_ChartColumn, animated: true },
  "Assignment": { C: Av_Clipboard, animated: true },
  "AssignmentInd": { C: Av_UserCheck, animated: true },
  "AssignmentTurnedIn": { C: FallbackIcon, animated: false, anim: "pop" },
  "Backup": { C: Av_CloudUpload, animated: true },
  "Badge": { C: FallbackIcon, animated: false, anim: "pulse" },
  "BarChart": { C: Av_ChartColumn, animated: true },
  "Block": { C: FallbackIcon, animated: false, anim: "shake" },
  "Notifications": { C: Av_Bell, animated: true },
  "Business": { C: FallbackIcon, animated: false, anim: "pop" },
  "CalendarMonth": { C: FallbackIcon, animated: false, anim: "pop" },
  "CalendarToday": { C: FallbackIcon, animated: false, anim: "pop" },
  "CallMade": { C: FallbackIcon, animated: false, anim: "slide" },
  "Cancel": { C: Av_X, animated: true },
  "CancelOutlined": { C: FallbackIcon, animated: false, anim: "shake" },
  "CancelTwoTone": { C: FallbackIcon, animated: false, anim: "shake" },
  "Category": { C: FallbackIcon, animated: false, anim: "pop" },
  "Check": { C: Av_Check, animated: true },
  "CheckCircle": { C: Av_CircleCheck, animated: true },
  "CheckCircleOutline": { C: Av_CircleCheck, animated: true },
  "CheckCircleTwoTone": { C: Av_CircleCheckBig, animated: true },
  "ChevronLeft": { C: Av_ChevronLeft, animated: true },
  "ChevronRight": { C: Av_ChevronRight, animated: true },
  "Clear": { C: Av_X, animated: true },
  "Close": { C: Av_X, animated: true },
  "CloudUpload": { C: Av_CloudUpload, animated: true },
  "Commute": { C: FallbackIcon, animated: false, anim: "slide" },
  "CompareArrows": { C: FallbackIcon, animated: false, anim: "slide" },
  "ContactPage": { C: Av_Contact, animated: true },
  "ContentCopy": { C: Av_Copy, animated: true },
  "ContentPaste": { C: FallbackIcon, animated: false, anim: "pop" },
  "CreditCard": { C: Av_CreditCard, animated: true },
  "CurrencyExchange": { C: FallbackIcon, animated: false, anim: "slide" },
  "CurrencyRupee": { C: Av_IndianRupee, animated: true },
  "Dashboard": { C: Av_Dashboard, animated: true },
  "Delete": { C: Av_Trash2, animated: true },
  "DeleteOutline": { C: Av_Trash2, animated: true },
  "DeleteTwoTone": { C: Av_Trash2, animated: true },
  "Description": { C: FallbackIcon, animated: false, anim: "pop" },
  "DirectionsRun": { C: FallbackIcon, animated: false, anim: "slide" },
  "DirectionsWalk": { C: FallbackIcon, animated: false, anim: "slide" },
  "Domain": { C: FallbackIcon, animated: false, anim: "pop" },
  "DoNotDisturbOnTwoTone": { C: FallbackIcon, animated: false, anim: "shake" },
  "Download": { C: Av_Download, animated: true },
  "Edit": { C: FallbackIcon, animated: false, anim: "wiggle" },
  "EditOutlined": { C: FallbackIcon, animated: false, anim: "wiggle" },
  "EditTwoTone": { C: FallbackIcon, animated: false, anim: "wiggle" },
  "Email": { C: Av_Mail, animated: true },
  "EmojiEvents": { C: FallbackIcon, animated: false, anim: "swing" },
  "Engineering": { C: FallbackIcon, animated: false, anim: "pop" },
  "Error": { C: FallbackIcon, animated: false, anim: "shake" },
  "ErrorOutline": { C: FallbackIcon, animated: false, anim: "shake" },
  "ErrorOutlineTwoTone": { C: FallbackIcon, animated: false, anim: "shake" },
  "EventAvailable": { C: FallbackIcon, animated: false, anim: "pop" },
  "EventNote": { C: FallbackIcon, animated: false, anim: "pop" },
  "EventRepeat": { C: FallbackIcon, animated: false, anim: "pop" },
  "ExitToApp": { C: Av_Logout, animated: true },
  "ExpandLess": { C: Av_ChevronUp, animated: true },
  "ExpandMore": { C: Av_ChevronDown, animated: true },
  "Factory": { C: FallbackIcon, animated: false, anim: "pop" },
  "FileDownload": { C: Av_Download, animated: true },
  "FilterAlt": { C: FallbackIcon, animated: false, anim: "wiggle" },
  "FilterAltOff": { C: FallbackIcon, animated: false, anim: "wiggle" },
  "FilterList": { C: Av_SlidersHorizontal, animated: true },
  "Flag": { C: FallbackIcon, animated: false, anim: "swing" },
  "GpsFixed": { C: FallbackIcon, animated: false, anim: "pop" },
  "GraphicEq": { C: Av_AudioLines, animated: true },
  "GridView": { C: Av_LayoutGrid, animated: true },
  "Group": { C: Av_Users, animated: true },
  "Groups": { C: Av_UsersRound, animated: true },
  "HighlightOff": { C: FallbackIcon, animated: false, anim: "shake" },
  "History": { C: FallbackIcon, animated: false, anim: "spin" },
  "Home": { C: Av_House, animated: true },
  "HomeWork": { C: FallbackIcon, animated: false, anim: "pop" },
  "HourglassEmpty": { C: FallbackIcon, animated: false, anim: "pop" },
  "HowToReg": { C: Av_UserCheck, animated: true },
  "Info": { C: Av_Info, animated: true },
  "InfoOutlined": { C: Av_Info, animated: true },
  "Inventory": { C: FallbackIcon, animated: false, anim: "pop" },
  "Inventory2": { C: Av_Boxes, animated: true },
  "Inventory2Outlined": { C: Av_Boxes, animated: true },
  "KeyboardArrowDown": { C: Av_ChevronDown, animated: true },
  "KeyboardArrowRight": { C: Av_ChevronRight, animated: true },
  "KeyboardArrowUp": { C: Av_ChevronUp, animated: true },
  "Language": { C: Av_Globe, animated: true },
  "ListAlt": { C: Av_LayoutList, animated: true },
  "LocalOffer": { C: FallbackIcon, animated: false, anim: "pop" },
  "LocalShipping": { C: FallbackIcon, animated: false, anim: "slide" },
  "LocationCity": { C: FallbackIcon, animated: false, anim: "pop" },
  "LocationOn": { C: Av_MapPin, animated: true },
  "Lock": { C: Av_Lock, animated: true },
  "LockPerson": { C: Av_UserLock, animated: true },
  "Logout": { C: Av_Logout, animated: true },
  "Map": { C: FallbackIcon, animated: false, anim: "pop" },
  "Menu": { C: Av_Menu, animated: true },
  "MenuBook": { C: Av_BookOpen, animated: true },
  "Mic": { C: Av_Mic, animated: true },
  "MonetizationOn": { C: Av_DollarSign, animated: true },
  "MoreVert": { C: Av_EllipsisVertical, animated: true },
  "MoveToInbox": { C: FallbackIcon, animated: false, anim: "bounce" },
  "MyLocation": { C: FallbackIcon, animated: false, anim: "pop" },
  "NoteAdd": { C: FallbackIcon, animated: false, anim: "bounce" },
  "Notes": { C: FallbackIcon, animated: false, anim: "pop" },
  "NotificationsActive": { C: Av_BellRing, animated: true },
  "OpenInNew": { C: Av_ExternalLink, animated: true },
  "Paid": { C: Av_BadgeDollar, animated: true },
  "Palette": { C: FallbackIcon, animated: false, anim: "pop" },
  "Payment": { C: Av_CreditCard, animated: true },
  "Payments": { C: Av_Wallet, animated: true },
  "Pending": { C: FallbackIcon, animated: false, anim: "pop" },
  "PendingActions": { C: FallbackIcon, animated: false, anim: "pop" },
  "PeopleAlt": { C: Av_UsersRound, animated: true },
  "Percent": { C: FallbackIcon, animated: false, anim: "pop" },
  "Person": { C: Av_User, animated: true },
  "PersonAdd": { C: Av_UserPlus, animated: true },
  "Phone": { C: Av_Phone, animated: true },
  "PhotoCamera": { C: FallbackIcon, animated: false, anim: "pop" },
  "PictureAsPdf": { C: FallbackIcon, animated: false, anim: "pop" },
  "Place": { C: Av_MapPin, animated: true },
  "PlayArrow": { C: Av_Play, animated: true },
  "PlayCircle": { C: FallbackIcon, animated: false, anim: "pop" },
  "PlayCircleOutline": { C: FallbackIcon, animated: false, anim: "pop" },
  "PlaylistAdd": { C: FallbackIcon, animated: false, anim: "bounce" },
  "PostAdd": { C: FallbackIcon, animated: false, anim: "bounce" },
  "PrecisionManufacturing": { C: FallbackIcon, animated: false, anim: "pop" },
  "Print": { C: FallbackIcon, animated: false, anim: "pop" },
  "Public": { C: Av_Globe, animated: true },
  "PublishedWithChanges": { C: FallbackIcon, animated: false, anim: "spin" },
  "RadioButtonUnchecked": { C: FallbackIcon, animated: false, anim: "pulse" },
  "Receipt": { C: FallbackIcon, animated: false, anim: "pop" },
  "ReceiptLong": { C: FallbackIcon, animated: false, anim: "pop" },
  "Refresh": { C: FallbackIcon, animated: false, anim: "spin" },
  "Remove": { C: Av_Minus, animated: true },
  "RemoveCircleOutline": { C: FallbackIcon, animated: false, anim: "shake" },
  "ReportProblem": { C: Av_TriangleAlert, animated: true },
  "RequestPage": { C: FallbackIcon, animated: false, anim: "pop" },
  "RequestQuote": { C: FallbackIcon, animated: false, anim: "pop" },
  "RestartAlt": { C: FallbackIcon, animated: false, anim: "spin" },
  "Route": { C: FallbackIcon, animated: false, anim: "slide" },
  "Save": { C: FallbackIcon, animated: false, anim: "pop" },
  "Scale": { C: FallbackIcon, animated: false, anim: "pop" },
  "Science": { C: FallbackIcon, animated: false, anim: "pop" },
  "Search": { C: Av_Search, animated: true },
  "SearchOff": { C: FallbackIcon, animated: false, anim: "shake" },
  "Security": { C: Av_ShieldCheck, animated: true },
  "SelectAll": { C: FallbackIcon, animated: false, anim: "pop" },
  "Send": { C: Av_Send, animated: true },
  "Settings": { C: Av_Settings, animated: true },
  "SettingsSuggest": { C: Av_Settings, animated: true },
  "Shield": { C: FallbackIcon, animated: false, anim: "pulse" },
  "ShoppingBag": { C: Av_ShoppingBag, animated: true },
  "ShoppingCart": { C: Av_ShoppingCart, animated: true },
  "ShowChart": { C: Av_ChartLine, animated: true },
  "SignalCellularAlt": { C: Av_Signal, animated: true },
  "Smartphone": { C: FallbackIcon, animated: false, anim: "pop" },
  "Sms": { C: Av_MessageCircle, animated: true },
  "Sort": { C: Av_ArrowDownUp, animated: true },
  "Speed": { C: FallbackIcon, animated: false, anim: "pop" },
  "StickyNote2Outlined": { C: FallbackIcon, animated: false, anim: "pop" },
  "Stop": { C: FallbackIcon, animated: false, anim: "pop" },
  "Store": { C: FallbackIcon, animated: false, anim: "pop" },
  "Storefront": { C: FallbackIcon, animated: false, anim: "pop" },
  "SupervisorAccount": { C: Av_UsersRound, animated: true },
  "SupportAgent": { C: Av_Headset, animated: true },
  "SwapHoriz": { C: FallbackIcon, animated: false, anim: "slide" },
  "SystemUpdate": { C: FallbackIcon, animated: false, anim: "pop" },
  "TableRows": { C: FallbackIcon, animated: false, anim: "pop" },
  "Timeline": { C: Av_Activity, animated: true },
  "Timer": { C: FallbackIcon, animated: false, anim: "pop" },
  "TrendingDown": { C: Av_TrendingDown, animated: true },
  "TrendingUp": { C: Av_TrendingUp, animated: true },
  "Tune": { C: Av_SlidersHorizontal, animated: true },
  "Upload": { C: Av_Upload, animated: true },
  "UploadFile": { C: Av_Upload, animated: true },
  "Verified": { C: FallbackIcon, animated: false, anim: "swing" },
  "VerifiedUser": { C: Av_ShieldCheck, animated: true },
  "Visibility": { C: Av_Eye, animated: true },
  "VisibilityOff": { C: Av_EyeOff, animated: true },
  "VisibilityTwoTone": { C: Av_Eye, animated: true },
  "Warehouse": { C: FallbackIcon, animated: false, anim: "pop" },
  "Warning": { C: Av_TriangleAlert, animated: true },
  "WarningAmber": { C: Av_TriangleAlert, animated: true },
  "WatchLater": { C: FallbackIcon, animated: false, anim: "pop" },
  "WhatsApp": { C: Av_MessageCircle, animated: true },
  "Wifi": { C: Av_Wifi, animated: true },
  "ViewKanban": { C: FallbackIcon, animated: false, anim: "pop" },
  "ViewList": { C: FallbackIcon, animated: false, anim: "pop" },
  "ViewModule": { C: Av_LayoutGrid, animated: true },
};

export const FALLBACK: IconEntry = { C: FallbackIcon, animated: false, anim: "pop" };

export function lookupIcon(name: string): IconEntry {
  const entry = ICON_MAP[name];
  if (!entry) {
    if (process.env.NODE_ENV !== "production") {
      // eslint-disable-next-line no-console
      console.warn(`[AppIcon] No mapping for "${name}" — using fallback.`);
    }
    return FALLBACK;
  }
  return entry;
}
