# Generated by Django 5.2.16 on 2026-07-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_distributorinvoice_request_distributorpayment'),
        ('foundation', '0007_eventdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='DistributorAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('damage', 'Damaged'), ('return', 'Returned'), ('audit', 'Stock Audit'), ('other', 'Other')], default='other', max_length=12)),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_adjustments', to='foundation.tenantuser')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='foundation.party')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_adjustments', to='foundation.catalogitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('shortage_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('plan_created', 'Plan Created'), ('in_production', 'In Production'), ('completed', 'Completed'), ('packed', 'Packed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='unpaid', max_length=12)),
                ('production_plan_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortage_items', to='distribution.distributorinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortages', to='foundation.catalogitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortages', to='distribution.stockrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('request', 'item')},
            },
        ),
    ]
