# Generated by Django 5.2.16 on 2026-07-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0005_party_assigned_agent_alter_party_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=20)),
                ('is_group', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('system_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='books.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('posting_date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sales_invoice', 'Sales Invoice'), ('payment', 'Payment Received'), ('purchase_bill', 'Purchase Bill'), ('opening', 'Opening Balance')], default='manual', max_length=20)),
                ('source_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='posted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posting_date', '-id'],
                'indexes': [models.Index(fields=['-posting_date'], name='books_journ_posting_3d784b_idx'), models.Index(fields=['source', 'source_ref'], name='books_journ_source_8703c7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('source_ref',), name='uniq_books_source_ref')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='books.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.journalentry')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='foundation.party')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='books_accou_account_77257e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'id'], name='books_journ_account_d52928_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['party', 'id'], name='books_journ_party_i_0664b5_idx'),
        ),
    ]
