# Generated by Django 5.2.16 on 2026-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_to_accounts', 'Sent to Accounts'), ('ordered', 'Ordered'), ('shipment_arrived', 'Shipment Arrived'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('stocked', 'Stocked'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='receipt_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipment_arrived', 'Shipment Arrived'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('stocked', 'Stocked'), ('short_closed', 'Short Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent to Supplier'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
