# Generated by Django 5.2.16 on 2026-07-18 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0006_tenantuser_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('system_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowance_claims', to='foundation.tenantuser')),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta_finance_approvals', to='foundation.tenantuser')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta_manager_approvals', to='foundation.tenantuser')),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Two-wheeler'), ('car', 'Car'), ('public', 'Public transport')], default='bike', max_length=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city', 'vehicle_type'],
                'unique_together': {('city', 'vehicle_type')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_mode', models.CharField(choices=[('bike', 'Two-wheeler'), ('car', 'Car'), ('public', 'Public transport')], default='bike', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('gps', 'GPS (tracked)')], default='manual', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='foundation.tenantuser')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='travel.allowanceclaim')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
