# Generated by Django 5.2.16 on 2026-07-18 11:01

import apps.travel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_eventdelivery'),
        ('travel', '0002_trip_basis_agentbankdetail_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.travel.models._claim_document_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(choices=[('receipt', 'Receipt'), ('toll', 'Toll'), ('fuel', 'Fuel'), ('other', 'Other')], default='receipt', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travel.allowanceclaim')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta_documents', to='foundation.tenantuser')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
