# Generated by Django 5.2.16 on 2026-07-31 05:30

import apps.travel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_allowancedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancedocument',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='allowancedocument',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.travel.models._claim_document_path),
        ),
    ]
