# Generated by Django 5.2.16 on 2026-07-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0005_party_assigned_agent_alter_party_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, choices=[('cold_calling', 'Cold Calling'), ('exhibition', 'Exhibition'), ('campaign', 'Campaign'), ('website', 'Website'), ('referral', 'Referral'), ('existing_customer', 'Existing Customer'), ('field_visit', 'Field Visit'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('interested', 'Interested'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='open', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('territory', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='foundation.tenantuser')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='foundation.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='crm_lead_status_d0e831_idx'),
        ),
    ]
