"use client";
import React, { useState, useEffect } from "react";
import {
  Box,
  Paper,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  IconButton,
  Tooltip,
  Chip,
  CircularProgress,
  Stack,
  useTheme,
  alpha,
  TextField,
  Button,
  Grid,
  InputAdornment,
  Avatar,
  Card,
  MenuItem,
  TableSortLabel,
  TablePagination,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Snackbar,
  Alert,
} from "@mui/material";
import { motion } from "framer-motion";

// Icons
import { DownloadIcon, ReceiptIcon, PictureAsPdfIcon, SearchIcon, FilterListIcon, RestartAltIcon, CalendarTodayIcon, ArrowForwardIcon, WarningAmberIcon, ErrorOutlineIcon, CheckCircleOutlineIcon, MenuBookIcon, PaidIcon } from "@/components/icons";

import { distributorService } from "@/lib/distributor-service";
import { salesService } from "@/lib/sales-service";
import { formatDRFError } from "@/lib/utils";

/**
 * DISTRIBUTOR CLIENT INVOICES PAGE
 * 
 * This page shows Sales Invoices generated by the Distributor for their Clients (Retailers).
 */

interface SalesInvoice {
  id: number;
  invoice_number: string;
  customer_name: string;
  invoice_date: string;
  due_date: string;
  total: number;
  outstanding_amount: number;
  payment_status: string;
  sales_order?: number;
}

export default function DistributorClientInvoicesPage() {
  const theme = useTheme();
  const [invoices, setInvoices] = useState<SalesInvoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState<number | null>(null);
  const [paymentDialogOpen, setPaymentDialogOpen] = useState(false);
  const [paymentRef, setPaymentRef] = useState("");
  const [selectedInvoice, setSelectedInvoice] = useState<SalesInvoice | null>(null);
  const [snackbar, setSnackbar] = useState({ open: false, message: "", severity: "success" as "success" | "error" });

  // Filters
  const [searchQuery, setSearchQuery] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [paymentStatus, setPaymentStatus] = useState("");
  const [ordering, setOrdering] = useState("-due_date"); // Default sort by due date descending
  const [showFilters, setShowFilters] = useState(false);

  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [totalCount, setTotalCount] = useState(0);

  // Stats
  const [unpaidCount, setUnpaidCount] = useState(0);
  const [partiallyPaidCount, setPartiallyPaidCount] = useState(0);
  const [paidCount, setPaidCount] = useState(0);

  useEffect(() => {
    fetchInvoices();
  }, [page, rowsPerPage, searchQuery, dateFrom, dateTo, paymentStatus, ordering]);

  useEffect(() => {
    fetchStats();
  }, []);

  const fetchStats = async () => {
    try {
      const [unpaidRes, partialRes, paidRes, totalRes] = await Promise.all([
        distributorService.getSalesInvoices({ payment_status: 'unpaid', page_size: '1' }),
        distributorService.getSalesInvoices({ payment_status: 'partially_paid', page_size: '1' }),
        distributorService.getSalesInvoices({ payment_status: 'paid', page_size: '1' }),
        distributorService.getSalesInvoices({ page_size: '1' })
      ]);
      setUnpaidCount(unpaidRes.count || 0);
      setPartiallyPaidCount(partialRes.count || 0);
      setPaidCount(paidRes.count || 0);
      setTotalCount(totalRes.count || 0);
    } catch (error) {
      console.error("Error fetching stats:", error);
    }
  };

  const fetchInvoices = async () => {
    try {
      setLoading(true);

      const params: Record<string, string> = {};
      if (searchQuery) params.search = searchQuery;
      if (dateFrom) {
        params.invoice_date__gte = dateFrom;
        // If only from date is set, default to today for the 'to' filter
        if (!dateTo) {
          params.invoice_date__lte = new Date().toISOString().split('T')[0];
        }
      }
      if (dateTo) params.invoice_date__lte = dateTo;
      if (paymentStatus) params.payment_status = paymentStatus;
      if (ordering) params.ordering = ordering;
      params.page = (page + 1).toString();
      params.page_size = rowsPerPage.toString();

      const response = await distributorService.getSalesInvoices(params);
      if (response.results) {
        setInvoices(response.results);
        setTotalCount(response.count || 0);
      } else if (Array.isArray(response)) {
        setInvoices(response);
        setTotalCount(response.length);
      }
    } catch (error) {
      console.error("Error fetching invoices:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(event.target.value);
  };

  const handleDateFromChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setDateFrom(event.target.value);
  };

  const handleDateToChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setDateTo(event.target.value);
  };

  const handlePaymentStatusChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPaymentStatus(event.target.value);
  };

  const handleRequestSort = (property: string) => {
    const isAsc = ordering === property;
    const newOrdering = isAsc ? `-${property}` : property;
    setOrdering(newOrdering);
    // Trigger fetch with new ordering
    fetchInvoicesWithParams({
      search: searchQuery,
      invoice_date__gte: dateFrom,
      invoice_date__lte: dateTo,
      payment_status: paymentStatus,
      ordering: newOrdering
    });
  };

  const fetchInvoicesWithParams = async (params: Record<string, string>) => {
    try {
      setLoading(true);
      const data = await distributorService.getSalesInvoices(params);
      setInvoices(data);
    } catch (error) {
      console.error("Error fetching invoices:", error);
    } finally {
      setLoading(false);
    }
  };


  const handleChangePage = (event: unknown, newPage: number) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  const handleResetFilters = () => {
    setSearchQuery("");
    setDateFrom("");
    setDateTo("");
    setPaymentStatus("");
    setOrdering("-due_date");
    setPage(0);
    fetchInvoicesAfterReset();
  };

  const fetchInvoicesAfterReset = async () => {
    try {
      setLoading(true);
      const data = await distributorService.getSalesInvoices({});
      if (data.results) {
        setInvoices(data.results);
        setTotalCount(data.count || 0);
      } else {
        setInvoices(data);
        setTotalCount(data.length);
      }
    } catch (error) {
      console.error("Error fetching invoices:", error);
    } finally {
      setLoading(false);
    }
  }

  const handleDownload = async (invoiceId: number, invoiceNumber: string) => {
    try {
      setDownloading(invoiceId);
      await distributorService.downloadSalesInvoicePDF(invoiceId, invoiceNumber);
    } catch (error) {
      console.error("Error downloading invoice:", error);
      alert(formatDRFError(error) || "Failed to download invoice");
    } finally {
      setDownloading(null);
    }
  };

  const handlePaymentSubmit = async () => {
    if (!selectedInvoice || !paymentRef || !selectedInvoice.sales_order) {
      if (!selectedInvoice?.sales_order) {
        setSnackbar({ open: true, message: "No linked Sales Order found for this invoice.", severity: "error" });
      }
      return;
    }

    try {
      setLoading(true);
      await salesService.markSalesOrderPaid(
        selectedInvoice.sales_order,
        paymentRef,
        selectedInvoice.total
      );
      setSnackbar({
        open: true,
        message: "Payment marked successfully",
        severity: "success",
      });
      setPaymentDialogOpen(false);
      setPaymentRef("");
      fetchInvoices();
    } catch (error: any) {
      setSnackbar({
        open: true,
        message: formatDRFError(error),
        severity: "error",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleMarkPaid = (invoice: SalesInvoice) => {
    setSelectedInvoice(invoice);
    setPaymentRef("");
    setPaymentDialogOpen(true);
  };

  const getStatusColor = (status: string) => {
    switch (status?.toLowerCase()) {
      case 'paid':
        return 'success';
      case 'partially_paid':
        return 'warning';
      case 'unpaid':
      case 'pending':
        return 'error';
      default:
        return 'default';
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      minimumFractionDigits: 2
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    if (!dateString) return "-";
    return new Date(dateString).toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric'
    });
  };

  return (
    <>
      <Box sx={{ maxWidth: '1600px', mx: 'auto' }}>
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          {/* Header Section */}
          <Stack
            direction={{ xs: 'column', md: 'row' }}
            justifyContent="space-between"
            alignItems={{ xs: 'flex-start', md: 'center' }}
            mb={4}
            spacing={2}
          >
            <Box>
              <Typography variant="h4" fontWeight={800} sx={{ letterSpacing: "-0.02em", color: 'text.primary' }}>
                Client Invoices
              </Typography>
              <Stack direction="row" alignItems="center" spacing={1} mt={0.5}>
                <Typography variant="body2" color="text.secondary">
                  Manage and track invoices issued to your clients
                </Typography>
              </Stack>
            </Box>

            <Stack direction="row" spacing={1.5} sx={{ flexWrap: 'wrap', gap: 1.5 }}>
              {/* Total Invoices Card */}
              <Card
                elevation={0}
                sx={{
                  p: 1.5,
                  minWidth: 140,
                  borderRadius: 1.5,
                  bgcolor: alpha(theme.palette.primary.main, 0.03),
                  border: `1px solid ${alpha(theme.palette.primary.main, 0.1)}`,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 1.5
                }}
              >
                <Box
                  sx={{
                    width: 36,
                    height: 36,
                    borderRadius: 1,
                    bgcolor: alpha(theme.palette.primary.main, 0.1),
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: 'primary.main'
                  }}
                >
                  <MenuBookIcon sx={{ fontSize: 20 }} />
                </Box>
                <Box>
                  <Typography variant="h6" fontWeight={800} color="primary.main">
                    {totalCount}
                  </Typography>
                  <Typography variant="caption" fontWeight={600} color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.05em', fontSize: '0.65rem' }}>
                    Total
                  </Typography>
                </Box>
              </Card>

              {/* Paid Invoices Card */}
              <Card
                elevation={0}
                sx={{
                  p: 1.5,
                  minWidth: 140,
                  borderRadius: 1.5,
                  bgcolor: alpha(theme.palette.success.main, 0.03),
                  border: `1px solid ${alpha(theme.palette.success.main, 0.1)}`,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 1.5
                }}
              >
                <Box
                  sx={{
                    width: 36,
                    height: 36,
                    borderRadius: 1,
                    bgcolor: alpha(theme.palette.success.main, 0.1),
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: 'success.main'
                  }}
                >
                  <CheckCircleOutlineIcon sx={{ fontSize: 20 }} />
                </Box>
                <Box>
                  <Typography variant="h6" fontWeight={800} color="success.main">
                    {paidCount}
                  </Typography>
                  <Typography variant="caption" fontWeight={600} color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.05em', fontSize: '0.65rem' }}>
                    Paid
                  </Typography>
                </Box>
              </Card>

              {/* Partially Paid Card */}
              <Card
                elevation={0}
                sx={{
                  p: 1.5,
                  minWidth: 140,
                  borderRadius: 1.5,
                  bgcolor: alpha(theme.palette.warning.main, 0.03),
                  border: `1px solid ${alpha(theme.palette.warning.main, 0.1)}`,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 1.5
                }}
              >
                <Box
                  sx={{
                    width: 36,
                    height: 36,
                    borderRadius: 1,
                    bgcolor: alpha(theme.palette.warning.main, 0.1),
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: 'warning.main'
                  }}
                >
                  <WarningAmberIcon sx={{ fontSize: 20 }} />
                </Box>
                <Box>
                  <Typography variant="h6" fontWeight={800} color="warning.main">
                    {partiallyPaidCount}
                  </Typography>
                  <Typography variant="caption" fontWeight={600} color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.05em', fontSize: '0.65rem' }}>
                    Partial
                  </Typography>
                </Box>
              </Card>

              {/* Unpaid Card */}
              <Card
                elevation={0}
                sx={{
                  p: 1.5,
                  minWidth: 140,
                  borderRadius: 1.5,
                  bgcolor: alpha(theme.palette.error.main, 0.03),
                  border: `1px solid ${alpha(theme.palette.error.main, 0.1)}`,
                  display: 'flex',
                  alignItems: 'center',
                  gap: 1.5
                }}
              >
                <Box
                  sx={{
                    width: 36,
                    height: 36,
                    borderRadius: 1,
                    bgcolor: alpha(theme.palette.error.main, 0.1),
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: 'error.main'
                  }}
                >
                  <ErrorOutlineIcon sx={{ fontSize: 20 }} />
                </Box>
                <Box>
                  <Typography variant="h6" fontWeight={800} color="error.main">
                    {unpaidCount}
                  </Typography>
                  <Typography variant="caption" fontWeight={600} color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.05em', fontSize: '0.65rem' }}>
                    Unpaid
                  </Typography>
                </Box>
              </Card>
            </Stack>

          </Stack>

          {/* Action Bar / Filters */}
          <Card
            elevation={0}
            sx={{
              p: 2,
              mb: 3,
              borderRadius: 1.5,
              bgcolor: "background.paper",
              boxShadow: "0px 4px 20px rgba(0,0,0,0.04)",
              border: `1px solid ${alpha(theme.palette.divider, 0.5)}`
            }}
          >
            <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} alignItems="center">

              {/* Search Field */}
              <Box sx={{ flexGrow: 1, minWidth: { md: 250 }, maxWidth: { md: 450 }, width: { xs: '100%', md: 'auto' } }}>
                <TextField
                  fullWidth
                  placeholder="Search by Client Name or Invoice #..."
                  value={searchQuery}
                  onChange={handleSearchChange}
                  size="small"
                  variant="outlined"
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <SearchIcon color="action" fontSize="small" />
                      </InputAdornment>
                    ),
                    sx: {
                      borderRadius: 1,
                      bgcolor: alpha(theme.palette.background.default, 0.5),
                      '& fieldset': { borderColor: 'transparent' },
                      '&:hover fieldset': { borderColor: alpha(theme.palette.primary.main, 0.2) },
                      '&.Mui-focused fieldset': { borderColor: theme.palette.primary.main },
                      transition: 'all 0.2s',
                      fontSize: '0.9rem'
                    }
                  }}
                />
              </Box>

              <Box sx={{ width: { xs: '100%', md: 180 } }}>
                <TextField
                  select
                  fullWidth
                  value={paymentStatus}
                  onChange={handlePaymentStatusChange}
                  size="small"
                  variant="outlined"
                  SelectProps={{
                    displayEmpty: true
                  }}
                  InputProps={{
                    sx: {
                      borderRadius: 1,
                      bgcolor: alpha(theme.palette.background.default, 0.5),
                      '& fieldset': { borderColor: 'transparent' },
                      '&:hover fieldset': { borderColor: alpha(theme.palette.primary.main, 0.2) },
                      '&.Mui-focused fieldset': { borderColor: theme.palette.primary.main },
                      transition: 'all 0.2s',
                      fontSize: '0.9rem',
                      color: paymentStatus ? 'text.primary' : 'text.secondary'
                    }
                  }}
                >
                  <MenuItem value="">All Statuses</MenuItem>
                  <MenuItem value="paid">Paid</MenuItem>
                  <MenuItem value="unpaid">Unpaid</MenuItem>
                  <MenuItem value="partially_paid">Partially Paid</MenuItem>
                </TextField>
              </Box>

              {/* Date Filters Controls */}
              <Stack direction="row" spacing={1} alignItems="center" sx={{ width: { xs: '100%', md: 'auto' } }}>
                <Box
                  sx={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '4px',
                    p: '2px',
                    borderRadius: 1.5,
                    border: '1px solid transparent',
                    bgcolor: alpha(theme.palette.background.default, 0.5),
                    transition: 'all 0.2s',
                    '&:focus-within': {
                      borderColor: theme.palette.primary.main,
                      bgcolor: 'background.paper',
                      boxShadow: `0 0 0 2px ${alpha(theme.palette.primary.main, 0.1)}`
                    },
                    '&:hover': {
                      borderColor: alpha(theme.palette.primary.main, 0.2)
                    }
                  }}
                >
                  <TextField
                    type="date"
                    value={dateFrom}
                    onChange={handleDateFromChange}
                    size="small"
                    variant="outlined"
                    sx={{
                      width: 160,
                      '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
                      '& .MuiOutlinedInput-root': {
                        fontSize: '0.85rem',
                        pr: 0.5
                      }
                    }}
                  />
                  <ArrowForwardIcon sx={{ fontSize: 14, color: 'text.disabled' }} />
                  <TextField
                    type="date"
                    value={dateTo}
                    onChange={handleDateToChange}
                    size="small"
                    variant="outlined"
                    sx={{
                      width: 160,
                      '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
                      '& .MuiOutlinedInput-root': {
                        fontSize: '0.85rem',
                        pr: 0.5
                      }
                    }}
                  />
                </Box>

                <Button
                  variant="outlined"
                  color="inherit"
                  onClick={handleResetFilters}
                  startIcon={<RestartAltIcon sx={{ fontSize: '1rem !important' }} />}
                  sx={{
                    height: 40,
                    borderRadius: 1.5,
                    textTransform: 'none',
                    px: 2,
                    fontWeight: 700,
                    fontSize: '0.875rem',
                    color: 'text.secondary',
                    borderColor: alpha(theme.palette.divider, 0.5),
                    '&:hover': {
                      borderColor: theme.palette.error.main,
                      color: theme.palette.error.main,
                      bgcolor: alpha(theme.palette.error.main, 0.05),
                    }
                  }}
                >
                  Clear
                </Button>
              </Stack>
            </Stack>
          </Card>

          {/* Invoices Table */}
          <Paper
            elevation={0}
            sx={{
              width: '100%',
              borderRadius: 1.5,
              border: `1px solid ${alpha(theme.palette.divider, 0.5)}`,
              bgcolor: "background.paper",
              boxShadow: "0px 10px 40px rgba(0,0,0,0.02)",
              overflow: "hidden",
            }}
          >
            <TableContainer>
              <Table sx={{ minWidth: 700 }}>
                <TableHead>
                  <TableRow sx={{ bgcolor: alpha(theme.palette.background.default, 0.4) }}>
                    <TableCell sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Invoice Details</TableCell>
                    <TableCell sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Client</TableCell>
                    <TableCell
                      sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}
                      sortDirection={ordering.includes('invoice_date') ? (ordering.startsWith('-') ? 'desc' : 'asc') : false}
                    >
                      <TableSortLabel
                        active={ordering.includes('invoice_date')}
                        direction={ordering.startsWith('-') ? 'desc' : 'asc'}
                        onClick={() => handleRequestSort('invoice_date')}
                      >
                        Date
                      </TableSortLabel>
                    </TableCell>
                    <TableCell
                      sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}
                      sortDirection={ordering.includes('due_date') ? (ordering.startsWith('-') ? 'desc' : 'asc') : false}
                    >
                      <TableSortLabel
                        active={ordering.includes('due_date')}
                        direction={ordering.startsWith('-') ? 'desc' : 'asc'}
                        onClick={() => handleRequestSort('due_date')}
                      >
                        Due Date
                      </TableSortLabel>
                    </TableCell>
                    <TableCell sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }} align="right">Amount</TableCell>
                    <TableCell sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }} align="right">Payable</TableCell>
                    <TableCell sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }} align="center">Status</TableCell>
                    <TableCell sx={{ py: 2, fontWeight: 600, color: 'text.secondary', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '0.05em' }} align="center">Action</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {loading ? (
                    <TableRow>
                      <TableCell colSpan={8} align="center" sx={{ py: 10 }}>
                        <CircularProgress size={40} thickness={4} />
                        <Typography variant="body2" color="text.secondary" mt={2}>Loading Invoices...</Typography>
                      </TableCell>
                    </TableRow>
                  ) : invoices.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={8} align="center" sx={{ py: 10 }}>
                        <Stack alignItems="center" spacing={2}>
                          <Box sx={{
                            width: 80, height: 80,
                            borderRadius: '50%',
                            bgcolor: alpha(theme.palette.background.default, 0.8),
                            display: 'flex', alignItems: 'center', justifyContent: 'center'
                          }}>
                            <ReceiptIcon sx={{ fontSize: 40, color: 'text.disabled' }} />
                          </Box>
                          <Box>
                            <Typography variant="h6" color="text.primary" fontWeight={600}>
                              No invoices found
                            </Typography>
                            <Typography variant="body2" color="text.secondary">
                              Try adjusting your filters or search criteria
                            </Typography>
                          </Box>
                        </Stack>
                      </TableCell>
                    </TableRow>
                  ) : (
                    invoices.map((invoice, index) => (
                      <TableRow
                        key={invoice.id}
                        hover
                        sx={{
                          '&:hover': {
                            bgcolor: alpha(theme.palette.primary.main, 0.01),
                            '& .action-btn': { opacity: 1 }
                          },
                          transition: 'all 0.2s'
                        }}
                      >
                        <TableCell>
                          <Stack>
                            <Typography variant="body2" fontWeight={700} color="primary.main">
                              {invoice.invoice_number}
                            </Typography>
                          </Stack>
                        </TableCell>
                        <TableCell>
                          <Stack direction="row" alignItems="center" spacing={1.5}>
                            <Avatar
                              sx={{
                                width: 32, height: 32,
                                fontSize: '0.85rem',
                                bgcolor: alpha(theme.palette.secondary.main, 0.1),
                                color: 'secondary.main',
                                fontWeight: 700
                              }}
                            >
                              {invoice.customer_name?.charAt(0) || "C"}
                            </Avatar>
                            <Typography variant="body2" fontWeight={600} color="text.primary">
                              {invoice.customer_name || "Unknown Client"}
                            </Typography>
                          </Stack>
                        </TableCell>
                        <TableCell>
                          <Typography variant="body2" fontWeight={500}>
                            {formatDate(invoice.invoice_date)}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography
                            variant="body2"
                            fontWeight={500}
                            color={new Date(invoice.due_date) < new Date() && invoice.payment_status !== 'paid' ? 'error.main' : 'text.primary'}
                          >
                            {formatDate(invoice.due_date)}
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body2" fontWeight={700} sx={{ fontFamily: 'monospace', fontSize: '0.95rem' }}>
                            {formatCurrency(invoice.total)}
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body2" fontWeight={700} sx={{ fontFamily: 'monospace', fontSize: '0.95rem', color: invoice.outstanding_amount > 0 ? 'error.main' : 'success.main' }}>
                            {formatCurrency(invoice.outstanding_amount)}
                          </Typography>
                        </TableCell>
                        <TableCell align="center">
                          <Chip
                            label={(invoice.payment_status || 'Unpaid').toUpperCase().replace('_', ' ')}
                            color={getStatusColor(invoice.payment_status)}
                            size="small"
                            variant="filled"
                            sx={{
                              fontWeight: 700,
                              fontSize: '0.65rem',
                              height: 24,
                              minWidth: 80,
                              borderRadius: 1.5,
                            }}
                          />
                        </TableCell>
                        <TableCell align="center">
                          <Stack direction="row" spacing={1} justifyContent="center" alignItems="center">
                            <Tooltip title="Download PDF">
                              <IconButton
                                onClick={() => handleDownload(invoice.id, invoice.invoice_number)}
                                disabled={downloading === invoice.id}
                                size="small"
                                className="action-btn"
                                sx={{
                                  color: 'error.main',
                                  bgcolor: alpha(theme.palette.error.main, 0.05),
                                  '&:hover': {
                                    bgcolor: alpha(theme.palette.error.main, 0.1),
                                    transform: 'scale(1.1)'
                                  },
                                  transition: 'all 0.2s',
                                  opacity: 0.7
                                }}
                              >
                                {downloading === invoice.id ? (
                                  <CircularProgress size={20} color="error" />
                                ) : (
                                  <PictureAsPdfIcon fontSize="small" />
                                )}
                              </IconButton>
                            </Tooltip>

                            {(invoice.payment_status === 'unpaid' || invoice.payment_status === 'partially_paid') && invoice.sales_order && (
                              <Tooltip title="Mark as Paid">
                                <IconButton
                                  onClick={() => handleMarkPaid(invoice)}
                                  size="small"
                                  className="action-btn"
                                  sx={{
                                    color: 'success.main',
                                    bgcolor: alpha(theme.palette.success.main, 0.05),
                                    '&:hover': {
                                      bgcolor: alpha(theme.palette.success.main, 0.1),
                                      transform: 'scale(1.1)'
                                    },
                                    transition: 'all 0.2s',
                                    opacity: 0.7
                                  }}
                                >
                                  <PaidIcon fontSize="small" />
                                </IconButton>
                              </Tooltip>
                            )}
                          </Stack>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </TableContainer>
            <TablePagination
              rowsPerPageOptions={[5, 10, 25, 50]}
              component="div"
              count={totalCount}
              rowsPerPage={rowsPerPage}
              page={page}
              onPageChange={handleChangePage}
              onRowsPerPageChange={handleChangeRowsPerPage}
              sx={{
                borderTop: `1px solid ${alpha(theme.palette.divider, 0.5)}`,
              }}
            />
          </Paper>
        </motion.div>
      </Box>

      <Dialog
        open={paymentDialogOpen}
        onClose={() => setPaymentDialogOpen(false)}
        PaperProps={{ sx: { borderRadius: 1 } }}
      >
        <DialogTitle sx={{ fontWeight: 800 }}>Mark Invoice as Paid</DialogTitle>
        <DialogContent>
          <Typography variant="body2" mb={2} color="text.secondary">
            Please enter the payment reference/UTR number to mark invoice{" "}
            <strong>{selectedInvoice?.invoice_number}</strong> as paid.
          </Typography>
          <TextField
            fullWidth
            label="Payment Reference"
            size="small"
            value={paymentRef}
            onChange={(e) => setPaymentRef(e.target.value)}
            autoFocus
            sx={{ mt: 1 }}
          />
        </DialogContent>
        <DialogActions sx={{ p: 2.5 }}>
          <Button onClick={() => setPaymentDialogOpen(false)} sx={{ fontWeight: 600 }}>Cancel</Button>
          <Button
            variant="contained"
            onClick={handlePaymentSubmit}
            disabled={!paymentRef || loading}
            sx={{ borderRadius: 2, fontWeight: 700, px: 3 }}
          >
            Confirm Payment
          </Button>
        </DialogActions>
      </Dialog>

      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={() => setSnackbar({ ...snackbar, open: false })}
        anchorOrigin={{ vertical: "bottom", horizontal: "right" }}
      >
        <Alert
          severity={snackbar.severity}
          variant="filled"
          sx={{ width: "100%", borderRadius: 2 }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </>
  );
}
