# Generated by Django 5.2.16 on 2026-07-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='adjustment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
